#theme: minima
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
title: Home Assistant - My Way
author: Matthias Kargel
description: Meine Dokumnetation für Home Assistant. Es ist mit Sicherheit nicht alles richtig und man kann vieles einfacher und anders machen, aber es geht um meinen Weg, nicht um den besten, einfachsten oder schnellsten Weg.
